services:
  namenode:
    image: ccr.ccs.tencentyun.com/hadoop-dev/hadoop:3.1.1
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    volumes:
      - ./data/namenode:/tmp/hadoop-hadoop/dfs/name

  datanode:
    image: ccr.ccs.tencentyun.com/hadoop-dev/hadoop:3.1.1
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - ./data/datanode:/tmp/hadoop-root/dfs/data

  resourcemanager:
    image: ccr.ccs.tencentyun.com/hadoop-dev/hadoop:3.1.1
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh

  nodemanager:
    image: ccr.ccs.tencentyun.com/hadoop-dev/hadoop:3.1.1
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
