apiVersion: v1
kind: Service
metadata:
  name: postgres-hive-db
  namespace: bigdata4
  labels:
    app: postgres-hive-db-internal
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-hive-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-hive-db-external
  namespace: bigdata4
  labels:
    app: postgres-hive-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-hive-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-hive-db
  namespace: bigdata4
spec:
  serviceName: postgres-hive-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-hive-db
  template:
    metadata:
      labels:
        app: postgres-hive-db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        imagePullPolicy: IfNotPresent

        command: ["/bin/bash", "-c"]
        args:
          - |
            PGDATA="/var/lib/postgresql/data/pgdata"
            PG_HBA_FILE="/var/lib/postgresql/data/pg_hba.conf"
            
            if [ ! -d "/var/lib/postgresql/data/base" ]; then
              echo "Initializing PostgreSQL data directory..."
              /usr/local/bin/docker-entrypoint.sh postgres &
              PG_PID=$!
              while [ ! -f "$PG_HBA_FILE" ]; do 
                sleep 1; 
              done
              echo "Initialization complete. Stopping temporary server."
              kill $PG_PID
              wait $PG_PID 2>/dev/null || true
            fi
            
            if [ -f "$PG_HBA_FILE" ]; then
              echo "Applying MD5 authentication fix to $PG_HBA_FILE"
              sed -i 's/scram-sha-256/md5/g' "$PG_HBA_FILE"
              echo "MD5 fix applied. Starting PostgreSQL service..."
            else
              echo "Error: pg_hba.conf file not found. Database startup may fail."
            fi
            
            exec /usr/local/bin/docker-entrypoint.sh postgres
            
        env:
          - name: POSTGRES_DB
            value: "hivedb"
          - name: POSTGRES_USER
            value: "hiveuser"
          - name: POSTGRES_PASSWORD
            value: "hivepassword"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata 
            
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local"
      resources:
        requests:
          storage: 5Gi
