apiVersion: v1
kind: Service
metadata:
  name: mysql-hive-db-internal
  namespace: bigdata4
  labels:
    app: mysql-hive-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP 
  selector:
    app: mysql-hive-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-hive-db-external
  namespace: bigdata4
  labels:
    app: mysql-hive-db
spec:
  type: NodePort 
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-hive-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-hive-db
  namespace: bigdata4
spec:
  serviceName: mysql-hive-db-internal 
  replicas: 1
  selector:
    matchLabels:
      app: mysql-hive-db
  template:
    metadata:
      labels:
        app: mysql-hive-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root_secure_password"
          - name: MYSQL_DATABASE
            value: "hivedb" #
          - name: MYSQL_USER
            value: "hiveuser"
          - name: MYSQL_PASSWORD
            value: "hivepassword"
            
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local"
      resources:
        requests:
          storage: 5Gi
