apiVersion: v1
kind: Service
metadata:
  name: postgres-hive-db-internal
  namespace: bigdata4
  labels:
    app: postgres-hive-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres-hive-db
---
# 2. 集群外访问Service（NodePort类型）
apiVersion: v1
kind: Service
metadata:
  name: postgres-hive-db-external
  namespace: bigdata4
  labels:
    app: postgres-hive-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
        #nodePort: 30432
      name: postgres
  selector:
    app: postgres-hive-db
---
# StatefulSet配置
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-hive-db
  namespace: bigdata4
spec:
  serviceName: postgres-hive-db-internal
  replicas: 1
  selector:
    matchLabels:
      app: postgres-hive-db
  template:
    metadata:
      labels:
        app: postgres-hive-db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_DB
            value: "hivedb"
          - name: POSTGRES_USER
            value: "hiveuser"
          - name: POSTGRES_PASSWORD
            value: "hivepassword"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "hiveuser", "-d", "hivedb"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "hiveuser", "-d", "hivedb"]
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local"
      resources:
        requests:
          storage: 5Gi
