apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: bigdata4
  labels:
    app: hadoop-datanode
spec:
  ports:
    - port: 9864
      name: web
    - port: 9866
      name: data
  clusterIP: None
  selector:
    app: hadoop-datanode
---
apiVersion: v1
kind: Service
metadata:
  name: datanode-external
  namespace: bigdata4
  labels:
    app: hadoop-datanode
spec:
  type: NodePort
  ports:
    - port: 9864
      name: web
      targetPort: 9864
    - port: 9866
      name: data
      targetPort: 9866
  selector:
    app: hadoop-datanode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  namespace: bigdata4
spec:
  serviceName: datanode
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-datanode
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
      - name: datanode
        image: zhuyifeiruichuang/hadoop:3.1.1
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "sudo mkdir -p /opt/hadoop/data/dn && sudo chown -R hadoop:hadoop /opt/hadoop/data && hdfs datanode"]
        env:
          - name: HADOOP_CONF_DIR
            value: "/opt/hadoop/etc/hadoop"
        ports:
          - containerPort: 9864
            name: web
          - containerPort: 9866
            name: data
        volumeMounts:
          - name: hadoop-dn-data
            mountPath: /opt/hadoop/data/dn
          - name: hadoop-config-volume
            mountPath: /opt/hadoop/etc/hadoop/core-site.xml
            subPath: core-site.xml
          - name: hadoop-config-volume
            mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
            subPath: hdfs-site.xml
          - name: hadoop-config-volume
            mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
            subPath: yarn-site.xml
      volumes:
        - name: hadoop-config-volume
          configMap:
            name: hadoop-config
  volumeClaimTemplates:
  - metadata:
      name: hadoop-dn-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local"
      resources:
        requests:
          storage: 20Gi
